<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Register</h2>
            <div class="form-group <?php if ($this->form->get('username')->getMessages()):?>has-error has-feedback<?php endif;?>">
                <label for="username">Username</label>
                <input id="username" name="username" type="text" class="form-control" placeholder="Enter Username">
                <?php if ($this->form->get('username')->getMessages()) : ?>
                    <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                    <?php foreach ($this->form->get('username')->getMessages() as $error) : ?>
                        <span class="help-block"><?= $error ?></span>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="form-group <?php if ($this->form->get('email')->getMessages()):?>has-error has-feedback<?php endif;?>">
                <label for="email">Email address</label>
                <input id="email" name="email" type="email" class="form-control" placeholder="Enter Email">
                <?php if ($this->form->get('email')->getMessages()) : ?>
                    <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                    <?php foreach ($this->form->get('email')->getMessages() as $error) : ?>
                        <span class="help-block"><?= $error ?></span>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="form-group <?php if ($this->form->get('password')->getMessages()):?>has-error has-feedback<?php endif;?>">
                <label for="password">Password</label>
                <input name="password" type="password" class="form-control" id="password" placeholder="Password">
                <?php if ($this->form->get('password')->getMessages()) : ?>
                    <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                    <?php foreach ($this->form->get('password')->getMessages() as $error) : ?>
                        <span class="help-block"><?= $error ?></span>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="form-group <?php if ($this->form->get('confirm_password')->getMessages()):?>has-error has-feedback<?php endif;?>">
                <label for="confirm_password">Confirm Password</label>
                <input name="confirm_password" type="password" class="form-control" id="confirm_password" placeholder="Confirm Password">
                <?php if ($this->form->get('confirm_password')->getMessages()) : ?>
                    <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                    <?php foreach ($this->form->get('confirm_password')->getMessages() as $error) : ?>
                        <span class="help-block"><?= $error ?></span>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <?= $this->formElement($this->form->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
        </form>
    </div>
</div>