<?php use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger; ?>
<?php $this->headTitle('Reset Password');?>
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <?= $this->flashMessenger()->render(FlashMessenger::NAMESPACE_INFO, ['alert', 'alert-dismissible', 'alert-info']);?>
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Reset Password</h2>
            <div class="form-group <?php if ($this->form->get('email')->getMessages()):?>has-error has-feedback<?php endif;?>">
                <label for="email">Email address</label>
                <input id="email" name="email" type="email" class="form-control" aria-describedby="email" placeholder="Enter email">
                <?php if ($this->form->get('email')->getMessages()) : ?>
                    <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                    <?php foreach ($this->form->get('email')->getMessages() as $error) : ?>
                        <span class="help-block"><?= $error ?></span>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <?= $this->formElement($this->form->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Send Password</button>
        </form>
    </div>
</div>